package org.iot.dsa.dslink.v2.mailer;

/**
 * Container for various helper variables and/or functions.
 *
 * @author James (Juris) Puchin
 * Created on 10/17/2017
 */
class Mailv2Helpers {
    ////////////////////
    //String Definitions
    ////////////////////
    static final String DEF_SUBJ = "Mail DSlink Alert";
    static final String DEF_BODY = "This alert was auto-generated by the DSA Mailer DSLink.";

    static final String DOCS = "Docs";

    static final String ADD_SMTP = "Connect SMTP";
    static final String ADD_GMAIL = "Connect Gmail";

    static final String CON_NAME = "Node Name";
    static final String E_USER = "User Name";
    static final String E_PASSWORD = "Password";
    static final String HOST = "Host Name";
    static final String PORT = "Port";

    static final String EDIT = "Edit";

    static final String DELETE = "Disconnect";

    static final String TO = "To";
    static final String CC = "Cc";
    static final String BCC = "Bcc";
    static final String FROM = "From";
    static final String SUBJ = "Subject";
    static final String BODY = "Body";
    static final String ATTACH = "Attachment";
    static final String SEND_MAIL = "Send Mail";
}
